import { calculateReport, getWeekRange } from './academic-core.js';

const SUPABASE_URL = 'https://jnqekougzmihjqffhuva.supabase.co';
const SUPABASE_KEY = 'sb_publishable_CbFnopBPwmFgfKfgQJGa8g_Qpbh6C5i';
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { storageKey: 'ep-auth-token', persistSession: true } });
const state = { user: null, profile: null, isAdmin: false, teachers: [], students: [], assignments: [], sessions: [], reports: [], tasks: [] };
const $ = s => document.querySelector(s);
const esc = value => String(value ?? '—').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const badge = value => `<span class="badge ${esc(value).replaceAll(' ','-')}">${esc(value)}</span>`;
const title = (name, sub, action='') => `<div class="page-head"><div><h1>${name}</h1><p>${sub}</p></div>${action}</div>`;
const table = (heads, rows) => `<table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${heads.length}">No records yet.</td></tr>`}</tbody></table>`;
const teacherName = id => state.teachers.find(t=>t.id===id)?.full_name || state.teachers.find(t=>t.id===id)?.email || 'Unassigned';
const studentName = id => state.students.find(s=>s.id===id)?.full_name || 'Student';

async function query(name, select='*', configure=q=>q) { const {data,error}=await configure(sb.from(name).select(select)); if(error) throw error; return data||[]; }
async function loadData() {
  const week=getWeekRange();
  const studentResult = sb.rpc('ep_students');
  const requests = [studentResult.then(({data,error})=>{if(error)throw error;return data||[]}), query('student_teacher_assignments'), query('class_sessions','*',q=>q.gte('date',week.start).lte('date',week.end)), query('weekly_reports','*',q=>q.order('week_start',{ascending:false})), query('teacher_tasks','*',q=>q.order('created_at',{ascending:false}))];
  if(state.isAdmin) requests.push(query('profiles','id,email,full_name,tier,is_admin',q=>q.eq('tier','teacher')));
  const [students,assignments,sessions,reports,tasks,teachers=[]]=await Promise.all(requests);
  Object.assign(state,{students,assignments,sessions,reports,tasks});
  state.teachers = state.isAdmin ? teachers : [{id:state.user.id,email:state.user.email,full_name:state.profile.full_name}];
}

function nav() {
  const admin=[['','Overview'],['directory','Teachers'],['students','Students'],['schedule','Schedule'],['reports','Weekly Reports'],['tasks','Tasks']];
  const teacher=[['','My Overview'],['students','My Students'],['schedule','My Schedule'],['reports','Weekly Report'],['tasks','My Tasks']];
  const page=location.pathname.replace(/^\/teachers\/?/,'').split('/')[0];
  $('#nav').innerHTML=(state.isAdmin?admin:teacher).map(([path,label])=>`<a class="nav-link ${page===path?'active':''}" href="/teachers/${path}">${label}</a>`).join('');
}

function overview() {
  const week=getWeekRange(), ownReport=state.reports.find(r=>r.teacher_user_id===state.user.id&&r.week_start===week.start);
  if(!state.isAdmin){
    const pending=state.tasks.filter(t=>t.status!=='Completed').length;
    return title('My Overview','Your students, schedule and weekly work at a glance.')+
      `<section class="report-cta"><h2>Create Weekly Report</h2><p>Report the hours you taught this week.</p>${ownReport?.status==='Submitted'?badge('Submitted'):`<button class="ep-btn-primary" data-action="report">${ownReport?'Continue report':'Create Weekly Report'}</button>`}${ownReport?.status==='Needs Changes'?`<p><strong>Changes requested:</strong> ${esc(ownReport.admin_comments)}</p>`:''}</section>`+
      stats([['Assigned students',state.students.length],['Classes this week',state.sessions.length],['Pending tasks',pending],['Report status',ownReport?.status||'Not started']]);
  }
  const activeTeachers=state.teachers.length, activeStudents=state.students.filter(s=>s.status==='Active').length;
  const pendingReports=state.reports.filter(r=>r.status==='Submitted').length, changes=state.reports.filter(r=>r.status==='Needs Changes').length;
  const submitted=new Set(state.reports.filter(r=>r.week_start===week.start&&r.status!=='Draft').map(r=>r.teacher_user_id));
  return title('Academic Overview','Administration for the current teaching week.')+stats([
    ['Active teachers',activeTeachers],['Active students',activeStudents],['Classes scheduled',state.sessions.filter(s=>s.status==='Scheduled').length],['Reports pending',pendingReports],['Need corrections',changes],['Reports missing',Math.max(0,activeTeachers-submitted.size)],['Pending tasks',state.tasks.filter(t=>t.status!=='Completed').length],['No-shows',state.sessions.filter(s=>s.status==='No-show').length]
  ])+`<div class="quick"><button class="ep-btn-primary" data-action="student">Add Student</button><button class="btn" data-action="assign">Assign Student</button><a class="btn link" href="/teachers/reports">View Weekly Reports</a><button class="btn" data-action="task">Create Task</button></div>`;
}
function stats(items){return `<div class="grid">${items.map(([label,value])=>`<article class="ep-card stat"><strong>${esc(value)}</strong><span>${label}</span></article>`).join('')}</div>`}

function directory(){return title('Teachers','Existing accounts with the Teacher tier.')+table(['Teacher','Email','Status','Students','Hours this week','Report','Pending tasks',''],state.teachers.map(t=>{
  const count=state.assignments.filter(a=>a.teacher_user_id===t.id&&a.status==='Active').length;
  const minutes=calculateReport(state.sessions.filter(s=>s.teacher_user_id===t.id)).totalBillableMinutes;
  const report=state.reports.find(r=>r.teacher_user_id===t.id&&r.week_start===getWeekRange().start);
  return `<tr><td>${esc(t.full_name||'Teacher')}</td><td>${esc(t.email)}</td><td>${badge('Active')}</td><td>${count}</td><td>${(minutes/60).toFixed(1)}</td><td>${badge(report?.status||'Missing')}</td><td>${state.tasks.filter(x=>x.assigned_teacher_id===t.id&&x.status!=='Completed').length}</td><td><a href="/teachers/directory/${t.id}">Open</a></td></tr>`}).join(''))}

function students(){return title(state.isAdmin?'Students':'My Students','Student records and active teacher assignments.',state.isAdmin?'<button class="ep-btn-primary" data-action="student">Add Student</button>':'')+
  `<div class="filters"><input id="studentSearch" placeholder="Search name or email"><select id="statusFilter"><option value="">All statuses</option>${['Active','Paused','Inactive','Prospect'].map(x=>`<option>${x}</option>`)}</select></div>`+
  table(['Student','Email','Level','Status','Teacher',''],state.students.map(s=>{const a=state.assignments.find(a=>a.student_id===s.id&&a.status==='Active');return `<tr data-student-row data-search="${esc((s.full_name+' '+(s.email||'')).toLowerCase())}" data-status="${s.status}"><td>${esc(s.full_name)}</td><td>${esc(s.email)}</td><td>${esc(s.level)}</td><td>${badge(s.status)}</td><td>${esc(teacherName(a?.teacher_user_id))}</td><td><a href="/teachers/students/${s.id}">Open</a></td></tr>`}).join(''))}

function studentDetail(id){const s=state.students.find(x=>x.id===id);if(!s)return title('Student unavailable','The record does not exist or you are not authorized to access it.');const a=state.assignments.find(x=>x.student_id===id&&x.status==='Active');return title(esc(s.full_name),`${esc(s.level)} · ${esc(s.status)}`,state.isAdmin?'<button class="btn" data-action="assign">Reassign</button>':'')+`<div class="tabs"><span>Overview</span><span>Schedule & Classes</span><span>Tasks</span><span>Notes</span><span>History</span></div><div class="grid"><article class="ep-card card"><h3>Basic information</h3><p>${esc(s.email)}<br>${esc(s.phone)}<br>${esc(s.company)}<br>${esc(s.timezone)}</p></article><article class="ep-card card"><h3>Current teacher</h3><p>${esc(teacherName(a?.teacher_user_id))}</p><p>${esc(s.classes_per_week)} classes/week · ${esc(s.default_class_duration)} minutes</p></article></div>`+table(['Date','Time','Status','Notes'],state.sessions.filter(x=>x.student_id===id).map(x=>`<tr><td>${x.date}</td><td>${x.start_time}</td><td>${badge(x.status)}</td><td>${esc(x.notes)}</td></tr>`).join(''))}

function schedule(){return title(state.isAdmin?'Schedule':'My Schedule','Sessions for the current Monday–Sunday week.')+table(['Date','Time','Student','Teacher','Duration','Status','Payable','Notes'],state.sessions.map(s=>`<tr><td>${s.date}</td><td>${s.start_time}–${s.end_time}</td><td>${esc(studentName(s.student_id))}</td><td>${esc(teacherName(s.teacher_user_id))}</td><td>${s.duration_minutes} min</td><td>${badge(s.status)}</td><td>${['Completed','Make-up class'].includes(s.status)||s.billing_status==='Billable no-show'?'Yes':'No'}</td><td>${esc(s.notes)}</td></tr>`).join(''))}

function reports(){return title(state.isAdmin?'Weekly Reports':'My Weekly Reports','Review teaching time, payable time and approval status.',!state.isAdmin?'<button class="ep-btn-primary" data-action="report">Create Weekly Report</button>':'')+table(['Week','Teacher','Taught','Payable','Classes','No-shows','Status','Actions'],state.reports.map(r=>`<tr><td>${r.week_start} – ${r.week_end}</td><td>${esc(teacherName(r.teacher_user_id))}</td><td>${(r.total_completed_minutes/60).toFixed(1)}h</td><td>${(r.total_billable_minutes/60).toFixed(1)}h</td><td>${r.total_completed_classes}</td><td>${r.total_no_shows}</td><td>${badge(r.status)}</td><td>${state.isAdmin&&r.status==='Submitted'?`<button class="btn" data-approve="${r.id}">Approve</button> <button class="btn" data-changes="${r.id}">Needs changes</button>`:''}</td></tr>`).join(''))}

function tasks(){return title(state.isAdmin?'Tasks':'My Tasks','Assignments and append-only comment history.',state.isAdmin?'<button class="ep-btn-primary" data-action="task">Create Task</button>':'')+table(['Task','Teacher','Student','Due','Status',''],state.tasks.map(t=>`<tr><td><strong>${esc(t.title)}</strong><br>${esc(t.description)}</td><td>${esc(teacherName(t.assigned_teacher_id))}</td><td>${esc(studentName(t.related_student_id))}</td><td>${esc(t.due_date)}</td><td><select data-task-status="${t.id}">${['Not Started','In Progress','Completed'].map(x=>`<option ${x===t.status?'selected':''}>${x}</option>`)}</select></td><td><button class="btn" data-comment="${t.id}">Comments</button></td></tr>`).join(''))}

function teacherDetail(id){if(!state.isAdmin)return title('Access denied','Teacher operational profiles are administrative only.');const t=state.teachers.find(x=>x.id===id);if(!t)return title('Teacher not found','This Teacher account is unavailable.');return title(esc(t.full_name||'Teacher'),esc(t.email))+`<div class="tabs"><span>Students</span><span>Schedule</span><span>Reports</span><span>Tasks</span><span>Admin notes</span></div>`+stats([['Assigned students',state.assignments.filter(a=>a.teacher_user_id===id&&a.status==='Active').length],['Classes this week',state.sessions.filter(s=>s.teacher_user_id===id).length],['Reports',state.reports.filter(r=>r.teacher_user_id===id).length],['Pending tasks',state.tasks.filter(x=>x.assigned_teacher_id===id&&x.status!=='Completed').length]])}

function render(){nav();const parts=location.pathname.replace(/^\/teachers\/?/,'').split('/').filter(Boolean);const page=parts[0]||'';$('#view').innerHTML=page==='directory'?(parts[1]?teacherDetail(parts[1]):directory()):page==='students'?(parts[1]?studentDetail(parts[1]):students()):page==='schedule'?schedule():page==='reports'?reports():page==='tasks'?tasks():overview();bind()}

function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
function formField(label,name,type='text',extra=''){return `<div class="field"><label>${label}</label><input name="${name}" type="${type}" ${extra}></div>`}
function studentForm(){openModal(`<h2 class="ep-heading">Add Student</h2><form id="studentForm">${formField('Full name','full_name','text','required')}${formField('Email','email','email')}${formField('Level','level')}${formField('Start date','start_date','date')}<div class="field"><label>Status</label><select name="status">${['Active','Paused','Inactive','Prospect'].map(x=>`<option>${x}</option>`)}</select></div>${formField('Classes per week','classes_per_week','number','min="0"')}${formField('Default duration','default_class_duration','number','value="60" min="1"')}<button class="ep-btn-primary">Save Student</button></form>`)}
function assignForm(){openModal(`<h2 class="ep-heading">Assign Student</h2><form id="assignForm"><div class="field"><label>Student</label><select name="student_id">${state.students.map(s=>`<option value="${s.id}">${esc(s.full_name)}</option>`)}</select></div><div class="field"><label>Teacher</label><select name="teacher_user_id">${state.teachers.map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`)}</select></div>${formField('Start date','start_date','date',`value="${new Date().toISOString().slice(0,10)}" required`)}<button class="ep-btn-primary">Assign</button></form>`)}
function taskForm(){openModal(`<h2 class="ep-heading">Create Task</h2><form id="taskForm">${formField('Title','title','text','required')}<div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Teacher</label><select name="assigned_teacher_id">${state.teachers.map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`)}</select></div>${formField('Due date','due_date','date')}<button class="ep-btn-primary">Create Task</button></form>`)}
function reportForm(){const week=getWeekRange(), sessions=state.sessions.filter(s=>s.teacher_user_id===state.user.id), totals=calculateReport(sessions);openModal(`<h2 class="ep-heading">Create Weekly Report</h2><p>${week.start} – ${week.end}</p>${table(['Student','Date','Time','Duration','Status','Payable','Notes'],sessions.map(s=>`<tr><td>${esc(studentName(s.student_id))}</td><td>${s.date}</td><td>${s.start_time}</td><td>${s.duration_minutes}</td><td>${esc(s.status)}</td><td>${['Completed','Make-up class'].includes(s.status)||s.billing_status==='Billable no-show'?'Yes':'No'}</td><td>${esc(s.notes)}</td></tr>`).join(''))}<div class="grid"><div class="stat"><strong>${totals.totalCompletedClasses}</strong><span>completed</span></div><div class="stat"><strong>${(totals.totalCompletedMinutes/60).toFixed(1)}h</strong><span>taught</span></div><div class="stat"><strong>${(totals.totalBillableMinutes/60).toFixed(1)}h</strong><span>payable</span></div><div class="stat"><strong>${totals.totalNoShows}</strong><span>no-shows</span></div></div><form id="reportForm"><textarea name="teacher_comments" placeholder="Comments for the admin"></textarea><button class="ep-btn-primary">Submit Weekly Report</button></form>`)}
async function comments(id){const rows=await query('task_comments','*',q=>q.eq('task_id',id).order('created_at'));openModal(`<h2 class="ep-heading">Task comments</h2>${rows.map(c=>`<div class="ep-card card"><p>${esc(c.comment)}</p><small>${new Date(c.created_at).toLocaleString()}</small></div>`).join('')||'<p>No comments yet.</p>'}<form id="commentForm" data-id="${id}"><textarea name="comment" required placeholder="Add a comment"></textarea><button class="ep-btn-primary">Add comment</button></form>`)}
async function mutate(promise,message){const {error}=await promise;if(error)throw error;show(message);closeModal();await loadData();render()}
function show(message){$('#notice').textContent=message;$('#notice').classList.add('show');setTimeout(()=>$('#notice').classList.remove('show'),3000)}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>({student:studentForm,assign:assignForm,task:taskForm,report:reportForm}[b.dataset.action]?.()));document.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>comments(b.dataset.comment));document.querySelectorAll('[data-task-status]').forEach(s=>s.onchange=()=>mutate(sb.from('teacher_tasks').update({status:s.value}).eq('id',s.dataset.taskStatus),'Task updated.'));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>mutate(sb.from('weekly_reports').update({status:'Approved',approved_at:new Date().toISOString()}).eq('id',b.dataset.approve),'Report approved.'));document.querySelectorAll('[data-changes]').forEach(b=>b.onclick=async()=>{const note=prompt('What should the teacher correct?');if(note)await mutate(sb.from('weekly_reports').update({status:'Needs Changes',admin_comments:note}).eq('id',b.dataset.changes),'Changes requested.')});$('#studentSearch')?.addEventListener('input',filterStudents);$('#statusFilter')?.addEventListener('change',filterStudents)}
function filterStudents(){const text=$('#studentSearch').value.toLowerCase(),status=$('#statusFilter').value;document.querySelectorAll('[data-student-row]').forEach(r=>r.hidden=!r.dataset.search.includes(text)||(status&&r.dataset.status!==status))}

document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));try{if(f.id==='studentForm')await mutate(sb.from('students').insert({...d,classes_per_week:Number(d.classes_per_week)||null,default_class_duration:Number(d.default_class_duration)}),'Student created.');if(f.id==='assignForm'){await sb.from('student_teacher_assignments').update({status:'Ended',end_date:d.start_date}).eq('student_id',d.student_id).eq('status','Active');await mutate(sb.from('student_teacher_assignments').insert({...d,status:'Active'}),'Student assigned.')}if(f.id==='taskForm')await mutate(sb.from('teacher_tasks').insert({...d,assigned_by_user_id:state.user.id,status:'Not Started'}),'Task created.');if(f.id==='commentForm')await mutate(sb.from('task_comments').insert({task_id:f.dataset.id,author_user_id:state.user.id,comment:d.comment}),'Comment preserved.');if(f.id==='reportForm'){if(!confirm('Submit this weekly report? You will not be able to edit it unless an admin requests changes.'))return;const week=getWeekRange(),sessions=state.sessions.filter(s=>s.teacher_user_id===state.user.id),t=calculateReport(sessions);await mutate(sb.from('weekly_reports').upsert({teacher_user_id:state.user.id,week_start:week.start,week_end:week.end,total_completed_minutes:t.totalCompletedMinutes,total_billable_minutes:t.totalBillableMinutes,total_completed_classes:t.totalCompletedClasses,total_no_shows:t.totalNoShows,status:'Submitted',teacher_comments:d.teacher_comments,submitted_at:new Date().toISOString()},{onConflict:'teacher_user_id,week_start'}),'Weekly report submitted.')}}catch(err){alert(err.message)}});
document.addEventListener('click',e=>{if(e.target.matches('[data-close]')||e.target.id==='modal')closeModal()});$('#signOut').onclick=async()=>{await sb.auth.signOut();location.href='/'};

async function init(){try{const {data:{session}}=await sb.auth.getSession();if(!session)throw new Error('denied');state.user=session.user;const {data:profile,error}=await sb.from('profiles').select('id,email,full_name,tier,is_admin').eq('id',session.user.id).single();if(error||(!profile?.is_admin&&String(profile?.tier).toLowerCase()!=='teacher'))throw new Error('denied');state.profile=profile;state.isAdmin=Boolean(profile.is_admin);await loadData();$('#identity').textContent=`${profile.full_name||session.user.email} · ${state.isAdmin?'Admin':'Teacher'}`;$('#loading').classList.add('hidden');$('#app').classList.remove('hidden');render()}catch(err){console.error(err);$('#loading').classList.add('hidden');$('#denied').classList.remove('hidden')}}init();
