import { LISTEN_WRITE_SETS, isCorrect, scorePercent, words } from './data.js';
const $ = id => document.getElementById(id);
const views = ['landing','difficulty','exercise','results'];
let set, mode, index=0, correct=0, submitted=false, chosen=[], missed=[];
function show(id){ views.forEach(v=>$(v).hidden=v!==id); scrollTo({top:0,behavior:'smooth'}); }
function renderSets(){ $('sets').innerHTML=LISTEN_WRITE_SETS.map(s=>`<article class="set-card"><div><span class="badge">Available to everyone</span><h2>${s.title}</h2><p>10 sentences · Easy, Medium, or Hard</p></div><button class="btn primary" data-set="${s.number}">Choose set →</button></article>`).join(''); }
function chooseSet(number){ set=LISTEN_WRITE_SETS.find(s=>s.number===number); if(set) show('difficulty'); }
function start(selected){ mode=selected; index=0; correct=0; missed=[]; renderItem(); show('exercise'); }
function renderItem(){ submitted=false; chosen=[]; const item=set.items[index]; $('count').textContent=`${index+1} of ${set.items.length}`; $('modeLabel').textContent=mode[0].toUpperCase()+mode.slice(1); $('bar').style.width=`${(index+1)/set.items.length*100}%`; $('audio').src=item.audio; $('check').disabled=false; $('check').hidden=false; $('next').hidden=true; $('feedback').className=''; $('feedback').textContent='';
  if(mode==='easy') renderEasy(item); else if(mode==='medium') renderMedium(item); else $('prompt').innerHTML='<label for="fullAnswer"><strong>Write what you hear</strong></label><textarea id="fullAnswer" class="full" autocomplete="off" spellcheck="false" aria-label="Write the complete sentence"></textarea>';
}
function renderEasy(item){ const all=words(item.answer); const scrambled=item.scramble.map(i=>({text:all[i],id:i})); $('prompt').innerHTML='<strong>Build the sentence</strong><div id="answerZone" class="answer-zone" aria-label="Your answer"></div><div id="wordBank" class="word-bank" aria-label="Available words"></div>'; scrambled.forEach(token=>addWord(token,'wordBank')); }
function addWord(token,target){ const b=document.createElement('button'); b.type='button'; b.className='word'; b.textContent=token.text; b.dataset.id=token.id; b.onclick=()=>{ if(submitted)return; if(target==='wordBank'){chosen.push(token); addWord(token,'answerZone')}else{chosen=chosen.filter(x=>x.id!==token.id); addWord(token,'wordBank')} b.remove(); }; $(target).append(b); }
function renderMedium(item){ let n=0; $('prompt').innerHTML='<strong>Type the missing words</strong><p>'+item.medium.split('[blank]').map((part,i,arr)=>part+(i<arr.length-1?`<input class="blank" data-blank="${n++}" autocomplete="off" spellcheck="false" aria-label="Missing word ${n}">`:'')).join('')+'</p>'; }
function answerFor(item){ if(mode==='easy')return chosen.map(x=>x.text).join(' '); if(mode==='hard')return $('fullAnswer').value; return [...document.querySelectorAll('[data-blank]')].map(i=>i.value); }
function check(){ if(submitted)return; const item=set.items[index]; const answer=answerFor(item); const ok=mode==='medium'?answer.every((v,i)=>isCorrect(v,item.blanks[i]))&&answer.length===item.blanks.length:isCorrect(answer,item.answer); submitted=true; if(ok)correct++; else missed.push({number:index+1,answer:item.answer}); $('feedback').className='feedback '+(ok?'good':'bad'); $('feedback').textContent=ok?'✓ Correct!':'✕ Not quite. The correct answer is: '+item.answer; $('check').disabled=true; $('check').hidden=true; $('next').hidden=false; $('next').textContent=index===set.items.length-1?'See results →':'Next →'; document.querySelectorAll('input,textarea,.word').forEach(el=>el.disabled=true); }
function next(){ if(index<set.items.length-1){index++;renderItem()}else finish(); }
function finish(){ const pct=scorePercent(correct,set.items.length); $('score').textContent=`Your score: ${pct}%`; $('correct').textContent=`${correct} / ${set.items.length}`; $('incorrect').textContent=`${set.items.length-correct} / ${set.items.length}`; $('completedMode').textContent=mode[0].toUpperCase()+mode.slice(1); $('review').innerHTML=missed.length?'<h3>Review incorrect sentences</h3><ol>'+missed.map(x=>`<li value="${x.number}">${x.answer}</li>`).join('')+'</ol>':'<div class="feedback good">Excellent — every answer was correct!</div>'; show('results'); window.parent.postMessage({type:'exerciseComplete',exerciseType:'Listen and Write',exerciseName:`Set ${set.number} — ${mode[0].toUpperCase()+mode.slice(1)}`,score:correct,maxScore:set.items.length,details:{activity:'Listen and Write',set:set.number,difficulty:mode,percentage:pct,correct,incorrect:set.items.length-correct,status:'completed',completedAt:new Date().toISOString()}},location.origin); }
$('play').onclick=async()=>{try{$('audio').currentTime=0;await $('audio').play();$('play').textContent='↻ Play again'}catch{$('play').textContent='Audio unavailable — try again'}}; $('audio').onended=()=>$('play').textContent='↻ Play again'; $('check').onclick=check; $('next').onclick=next; $('retry').onclick=()=>start(mode); document.addEventListener('click',e=>{const s=e.target.closest('[data-set]');if(s)chooseSet(Number(s.dataset.set));const m=e.target.closest('[data-mode]');if(m)start(m.dataset.mode);if(e.target.closest('[data-back]'))show('landing')}); renderSets();
