import { businessCases, getBusinessCase } from '/src/data/businessCases.js';
import { initialiseBusinessCasesTheme } from '/businesscases/theme.js';
initialiseBusinessCasesTheme();
const app=document.querySelector('#app');
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const directAudioUrl=url=>{if(!url)return '';try{const parsed=new URL(url);if(parsed.hostname.endsWith('dropbox.com')){parsed.hostname='dl.dropboxusercontent.com';parsed.searchParams.delete('dl');parsed.searchParams.set('raw','1')}return parsed.toString()}catch{return url}};
const badge=item=>`<span class="badge">${esc(item)}</span>`;
function catalogue(){app.innerHTML=`<header class="hero"><span class="eyebrow">Business English</span><h1>Business Cases</h1><p>Analyse realistic business situations while practising reading, listening, speaking, and writing.</p></header><div class="filters" role="group" aria-label="Filter cases by level">${['All levels','B1','B2','C1'].map((x,i)=>`<button class="filter" data-level="${i?x:'all'}" aria-pressed="${i===0}">${x}</button>`).join('')}</div><p class="note">Levels are guidance only. Students at other levels can complete any case with suitable guidance.</p><section class="case-grid" aria-live="polite"></section>`;const grid=app.querySelector('.case-grid');const draw=level=>{const items=level==='all'?businessCases:businessCases.filter(x=>x.level===level);grid.innerHTML=items.map(x=>`<article class="case-card"><img src="${esc(x.imageUrl)}" alt="${esc(x.imageAlt)}"><div class="card-body"><div class="meta">${badge(x.level)}${badge(x.category)}${badge(x.estimatedTime)}</div><h2>${esc(x.title)}</h2><p>${esc(x.summary)}</p><a class="btn primary" href="/businesscases/${encodeURIComponent(x.slug)}">Open case</a></div></article>`).join('')};draw('all');app.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{app.querySelectorAll('.filter').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw(b.dataset.level)})}
function section(id,title,skill,content){return `<section class="section"><button class="section-toggle" data-section="${id}" aria-expanded="true" aria-controls="panel-${id}">${esc(title)}<span class="skill">${esc(skill)}</span><span class="chevron" aria-hidden="true">⌄</span></button><div class="section-content" id="panel-${id}"><div class="section-inner"><div class="section-pad">${content}</div></div></div></section>`}
function audioMarkup(c){return `<div class="audio-player"><audio preload="metadata" src="${esc(directAudioUrl(c.listening.audioUrl))}"></audio><div class="audio-controls"><button class="icon-btn play" aria-label="Play audio">▶</button><button class="icon-btn rewind" aria-label="Rewind 10 seconds">↶ 10</button><button class="icon-btn forward" aria-label="Fast forward 10 seconds">10 ↷</button><span class="time">0:00 / 0:00</span><label>Volume <input class="volume" type="range" min="0" max="1" step=".05" value="1"></label><label>Speed <select class="speed"><option>.75</option><option selected>1</option><option>1.25</option><option>1.5</option></select>×</label></div><input class="progress" aria-label="Audio progress" type="range" min="0" max="100" value="0"><p class="audio-error" ${c.listening.audioUrl?'hidden':''}>Demonstration audio has not been added yet. Add a Dropbox sharing URL to this case’s <code>listening.audioUrl</code>.</p></div>`}
function quizMarkup(c){return `<form class="quiz">${c.comprehensionQuestions.map((q,i)=>`<div class="quiz-question" data-id="${q.id}"><fieldset><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map(o=>`<label class="option" data-option="${o.id}"><input type="radio" name="${q.id}" value="${o.id}"> ${esc(o.text)}</label>`).join('')}<p class="explanation" hidden></p></fieldset></div>`).join('')}<p class="form-error" hidden>Please answer all five questions before checking.</p><p class="result" hidden></p><button class="btn primary check" type="submit">Check answers</button> <button class="btn retry" type="button" hidden>Try again</button></form>`}
function conversationMarkup(c){return `<div class="conversation"><div class="conversation-card"><span class="counter"></span><p class="question-text"></p></div><div class="nav-actions"><button class="btn previous">Previous question</button><button class="btn primary next">Next question</button></div></div>`}
function writingMarkup(c){const w=c.writingTask;return `<h3>${esc(w.title)}</h3><p>${esc(w.instructions)}</p><div class="writing-meta"><strong>Suggested format:</strong> ${esc(w.format)} · <strong>Word range:</strong> ${esc(w.wordRange)}<div class="columns"><div><h4>Tips</h4><ul>${w.tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>Useful phrases</h4><ul>${w.usefulPhrases.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div><h4>Planning questions</h4><ul>${w.planningQuestions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></div><label for="response"><strong>Your response</strong></label><textarea id="response" class="response" placeholder="Start writing here…"></textarea><p class="word-count" aria-live="polite">0 words</p><div class="writing-actions"><button class="btn clear-writing">Clear response</button><button class="btn primary copy-writing">Copy response</button></div>`}
function renderCase(c){app.innerHTML=`<div class="lesson"><a class="back" href="/businesscases">← All business cases</a><header class="case-head"><span class="eyebrow">Business case</span><h1 class="case-title">${esc(c.title)}</h1><div class="meta">${badge(`Suggested ${c.level}`)}${badge(c.category)}${badge(c.estimatedTime)}</div><p>${esc(c.introduction)}</p></header><img class="case-photo" src="${esc(c.imageUrl)}" alt="${esc(c.imageAlt)}">${section('context',c.context.title,'Reading',c.context.paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''))}${section('listening',c.listening.title,'Listening',audioMarkup(c))}${section('comprehension','Comprehension','Reading & listening',quizMarkup(c))}${section('conversation','Conversation','Speaking',conversationMarkup(c))}${section('writing','Writing','Writing',writingMarkup(c))}</div>`;wireCase(c)}
const formatTime=n=>Number.isFinite(n)?`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`:'0:00';
function wireCase(c){document.querySelectorAll('.section-toggle').forEach(b=>{const key=`businessCase:${c.slug}:section:${b.dataset.section}`;const open=sessionStorage.getItem(key)!=='closed';b.setAttribute('aria-expanded',String(open));document.querySelector(`#panel-${b.dataset.section}`).classList.toggle('closed',!open);b.onclick=()=>{const next=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(next));document.querySelector(`#panel-${b.dataset.section}`).classList.toggle('closed',!next);sessionStorage.setItem(key,next?'open':'closed')}});wireAudio();wireQuiz(c);wireConversation(c);wireWriting(c)}
function wireAudio(){const audio=document.querySelector('audio');const play=document.querySelector('.play'),progress=document.querySelector('.progress'),time=document.querySelector('.time');play.onclick=()=>audio.paused?audio.play().catch(()=>document.querySelector('.audio-error').hidden=false):audio.pause();audio.onplay=()=>{play.textContent='❚❚';play.ariaLabel='Pause audio'};audio.onpause=()=>{play.textContent='▶';play.ariaLabel='Play audio'};audio.ontimeupdate=()=>{progress.value=audio.duration?audio.currentTime/audio.duration*100:0;time.textContent=`${formatTime(audio.currentTime)} / ${formatTime(audio.duration)}`};audio.onerror=()=>document.querySelector('.audio-error').hidden=false;progress.oninput=()=>{if(audio.duration)audio.currentTime=progress.value/100*audio.duration};document.querySelector('.rewind').onclick=()=>audio.currentTime=Math.max(0,audio.currentTime-10);document.querySelector('.forward').onclick=()=>audio.currentTime=Math.min(audio.duration||0,audio.currentTime+10);document.querySelector('.volume').oninput=e=>audio.volume=e.target.value;document.querySelector('.speed').onchange=e=>audio.playbackRate=e.target.value}
function wireQuiz(c){const form=document.querySelector('.quiz');form.onsubmit=e=>{e.preventDefault();const missing=c.comprehensionQuestions.filter(q=>!form.elements[q.id].value);form.querySelector('.form-error').hidden=!missing.length;form.querySelectorAll('.quiz-question').forEach(x=>x.classList.toggle('unanswered',missing.some(q=>q.id===x.dataset.id)));if(missing.length)return;let score=0;c.comprehensionQuestions.forEach(q=>{const chosen=form.elements[q.id].value;if(chosen===q.correctAnswer)score++;form.querySelector(`[data-id="${q.id}"]`).querySelectorAll('.option').forEach(o=>{o.classList.toggle('correct',o.dataset.option===q.correctAnswer);o.classList.toggle('incorrect',o.dataset.option===chosen&&chosen!==q.correctAnswer)});const exp=form.querySelector(`[data-id="${q.id}"] .explanation`);exp.hidden=false;exp.textContent=`Correct answer: ${q.correctAnswer.toUpperCase()}. ${q.explanation}`});form.querySelector('.result').hidden=false;form.querySelector('.result').textContent=`Your score: ${score} / ${c.comprehensionQuestions.length}`;form.querySelector('.check').hidden=true;form.querySelector('.retry').hidden=false};form.querySelector('.retry').onclick=()=>{form.reset();form.querySelectorAll('.correct,.incorrect,.unanswered').forEach(x=>x.classList.remove('correct','incorrect','unanswered'));form.querySelectorAll('.explanation,.result,.form-error,.retry').forEach(x=>x.hidden=true);form.querySelector('.check').hidden=false}}
function wireConversation(c){let i=0;const draw=()=>{document.querySelector('.counter').textContent=`Question ${i+1} of ${c.conversationQuestions.length}`;document.querySelector('.question-text').textContent=c.conversationQuestions[i];document.querySelector('.previous').disabled=i===0;const next=document.querySelector('.next');next.disabled=i===c.conversationQuestions.length-1;next.textContent=i===c.conversationQuestions.length-1?'Discussion complete':'Next question'};document.querySelector('.previous').onclick=()=>{if(i)i--;draw()};document.querySelector('.next').onclick=()=>{if(i<c.conversationQuestions.length-1)i++;draw()};draw()}
function wireWriting(c){const area=document.querySelector('.response'),count=document.querySelector('.word-count'),key=`businessCase:${c.slug}:draft`;area.value=localStorage.getItem(key)||'';const update=()=>{const words=area.value.trim()?area.value.trim().split(/\s+/).length:0;count.textContent=`${words} ${words===1?'word':'words'}`;localStorage.setItem(key,area.value)};area.oninput=update;update();document.querySelector('.clear-writing').onclick=()=>{area.value='';update();area.focus()};document.querySelector('.copy-writing').onclick=async()=>{await navigator.clipboard.writeText(area.value);document.querySelector('.copy-writing').textContent='Copied!';setTimeout(()=>document.querySelector('.copy-writing').textContent='Copy response',1200)}}
const slug=decodeURIComponent(location.pathname.replace(/^\/businesscases\/?/,'').split('/')[0]);if(!slug)catalogue();else{const c=getBusinessCase(slug);if(c)renderCase(c);else app.innerHTML='<div class="hero"><h1>Case not found</h1><p><a href="/businesscases" style="color:white">Return to Business Cases</a></p></div>'}
export { directAudioUrl };
