-- Account closure support.
-- The API uses the service role because deleting an Auth identity must never be
-- exposed to the browser. Academic records keep their existing references; Auth
-- identities are soft-deleted by the API so required operational history remains.

create table if not exists public.account_closure_events (
  id bigint generated by default as identity primary key,
  closed_at timestamptz not null default now(),
  subscription_cancelled boolean not null default false
);

alter table public.account_closure_events enable row level security;
revoke all on table public.account_closure_events from anon, authenticated;
grant insert on table public.account_closure_events to service_role;
grant usage, select on sequence public.account_closure_events_id_seq to service_role;

create or replace function public.prepare_account_closure(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_id is null then
    raise exception 'A user id is required';
  end if;

  -- Student academic records are intentionally retained and already use
  -- ON DELETE SET NULL for their account link. The Auth soft-delete retains the
  -- referenced identity needed by operational teacher/audit records.
  delete from public.profiles where id = p_user_id;
end;
$$;

revoke all on function public.prepare_account_closure(uuid) from public, anon, authenticated;
grant execute on function public.prepare_account_closure(uuid) to service_role;

notify pgrst, 'reload schema';
